version: '3.8'
services:
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./BookHeaven
    ports:
      - "5176:5176"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=BookHeaven;Username=postgres;Password=yourpassword

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: BookHeaven
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
