version: '3.8'
services:
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://34.192.89.242:5176

  backend:
    build: ./BookHeaven
    ports:
      - "5176:5176"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5176
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=BookHeaven;Username=postgres;Password=yourpassword
    networks:
      - app-network

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: BookHeaven
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
